#One way to use this:
#curl https://raw.githubusercontent.com/ebonetti/tatic/master/docker-compose.yml | DOMAIN=example.com EMAIL=email@example.com PATH2DATA=/var/www docker-compose -f - config | tee docker-compose.yml
version: '3'
services:
  certbot:
    image: ebonetti/certbot-integration
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - website-data:/var/www/:ro
      - certificates:/etc/letsencrypt/
      - acme-challenge:/var/www-acme-challenge/
    logging:
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "10"
  nginx:
    image: ebonetti/tatic
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - CERT=/etc/letsencrypt/live/${DOMAIN}
    volumes:
      - website-data:/var/www/:ro
      - certificates:/etc/letsencrypt/:ro
      - acme-challenge:/var/www-acme-challenge/:ro
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  certificates:
  acme-challenge:
  website-data:
    driver: local
    driver_opts:
      device: ${PATH2DATA}
      o: bind